### ISSUE TITLE
Argument #1 ($storage) must be of type Tymon\\JWTAuth\\Contracts\\Providers\\Storage, PHPOpenSourceSaver\\JWTAuth\\Providers\\Storage\\Illuminate given, called in /var/www/html/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php on line 280"

### ISSUE THREAD

**Issue by doenikoe** [bagisto/headless-ecommerce#57]
I've followed your instructions to setup headless-ecommerce but I got this error when opening GraphQL playgroud in my localhost. Any help will be much appreciated. Thank you!

My environment:
PHP 8.1.1
Apache2

<img width="1786" alt="Screen Shot 2022-06-13 at 09 29 16" src="https://user-images.githubusercontent.com/1280444/173269051-5e8a5136-8da0-423c-a37f-67a0f2b23eba.png">

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked and Found that the Issue is Fixed and Just what is need to be done just after the bagisto installation run the command

**composer require bagisto/graphql-api:dev-main**

**Video/Screenshot**

https://user-images.githubusercontent.com/92721837/189622744-718fcb3c-5369-466f-91f8-bde2b3e2db90.mp4
